spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: admin
application:
  repository: CountryFile
countries:
  - name: Scotland
    path: /flags/_scotland.png
    capital: Edinburgh
    borders:
      - England
  - name: France
    path: /flags/fr.png
    capital: Paris
    borders:
      - Belgium
      - Luxembourg
      - Germany
      - Switzerland
      - Italy